"""initial schema

Revision ID: 2bbf3ba70060
Revises:
Create Date: 2026-09-22 13:37:41.729385

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2bbf3ba70060'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_read', sa.Integer(), nullable=True),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('rows_rejected', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('site_id'),
    sa.UniqueConstraint('site_code')
    )
    op.create_table('buildings',
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('building_code', sa.String(length=120), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('primary_use', sa.String(length=100), nullable=True),
    sa.Column('area_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sub_primary_use', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('year_built', sa.SmallInteger(), nullable=True),
    sa.Column('number_of_floors', sa.SmallInteger(), nullable=True),
    sa.Column('occupants', sa.Integer(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('subindustry', sa.String(length=100), nullable=True),
    sa.Column('heating_type', sa.String(length=100), nullable=True),
    sa.Column('eui', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('site_eui', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source_eui', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('leed_level', sa.String(length=30), nullable=True),
    sa.Column('energy_star_rating', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('building_id'),
    sa.UniqueConstraint('building_code')
    )
    op.create_index('ix_buildings_site_id', 'buildings', ['site_id'], unique=False)
    op.create_table('weather_measurements',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('air_temp_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cloud_coverage', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('dew_temp_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('precip_1hr_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('precip_6hr_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sea_lvl_pressure', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('wind_direction', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_speed', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('site_id', 'ts')
    )
    op.create_table('sensors',
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('meter_type', sa.String(length=30), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], ),
    sa.PrimaryKeyConstraint('sensor_id'),
    sa.UniqueConstraint('building_id', 'meter_type')
    )
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.sensor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_sensor_ts', 'alerts', ['sensor_id', 'ts'], unique=False)
    op.create_index('ix_alerts_unresolved', 'alerts', ['resolved'], unique=False, postgresql_where=sa.text('resolved = false'))
    op.create_table('energy_measurements',
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumption_kwh', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.sensor_id'], ),
    sa.PrimaryKeyConstraint('sensor_id', 'ts')
    )
    op.create_index('ix_energy_measurements_ts', 'energy_measurements', ['ts'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('target_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('predicted_kwh', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('actual_kwh', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.sensor_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sensor_id', 'target_ts', 'model_name', 'model_version')
    )
    op.create_index('ix_predictions_sensor_target', 'predictions', ['sensor_id', 'target_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_predictions_sensor_target', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_energy_measurements_ts', table_name='energy_measurements')
    op.drop_table('energy_measurements')
    op.drop_index('ix_alerts_unresolved', table_name='alerts', postgresql_where=sa.text('resolved = false'))
    op.drop_index('ix_alerts_sensor_ts', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('sensors')
    op.drop_table('weather_measurements')
    op.drop_index('ix_buildings_site_id', table_name='buildings')
    op.drop_table('buildings')
    op.drop_table('sites')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
