"""add model_versions table and predictions.horizon

Revision ID: 417d3ee13de9
Revises: 2bbf3ba70060
Create Date: 2026-09-22 14:58:26.096874

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '417d3ee13de9'
down_revision: Union[str, Sequence[str], None] = '2bbf3ba70060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('feature_version', sa.String(length=20), nullable=False),
    sa.Column('train_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('train_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validation_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validation_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('test_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('test_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact_path', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('model_name', 'model_version')
    )
    op.add_column('predictions', sa.Column('horizon', sa.SmallInteger(), nullable=True))
    op.create_foreign_key(
        'fk_predictions_model_version', 'predictions', 'model_versions',
        ['model_name', 'model_version'], ['model_name', 'model_version'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_predictions_model_version', 'predictions', type_='foreignkey')
    op.drop_column('predictions', 'horizon')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
