"""add anomaly detection fields to alerts and synthetic_anomalies table

Revision ID: c072cc66140a
Revises: 417d3ee13de9
Create Date: 2026-09-22 17:06:15.850720

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c072cc66140a'
down_revision: Union[str, Sequence[str], None] = '417d3ee13de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synthetic_anomalies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anomaly_type', sa.String(length=30), nullable=False),
    sa.Column('original_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('injected_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('split', sa.String(length=20), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.sensor_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sensor_id', 'ts', 'seed', name='uq_synthetic_anomalies_point')
    )
    op.create_index('ix_synthetic_anomalies_split', 'synthetic_anomalies', ['split'], unique=False)
    op.add_column('alerts', sa.Column('anomaly_type', sa.String(length=30), nullable=False))
    op.add_column('alerts', sa.Column('detector_version', sa.String(length=20), nullable=False))
    op.add_column('alerts', sa.Column('residual', sa.Numeric(precision=12, scale=4), nullable=True))
    op.create_unique_constraint('uq_alerts_idempotency', 'alerts', ['sensor_id', 'ts', 'method', 'detector_version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_alerts_idempotency', 'alerts', type_='unique')
    op.drop_column('alerts', 'residual')
    op.drop_column('alerts', 'detector_version')
    op.drop_column('alerts', 'anomaly_type')
    op.drop_index('ix_synthetic_anomalies_split', table_name='synthetic_anomalies')
    op.drop_table('synthetic_anomalies')
    # ### end Alembic commands ###
